### ISSUE TITLE
CSV formatter should not hardcode us-ascii encoding

### ISSUE THREAD

**Issue by ghost** [stdunbar/jisql#1]
Hi,

we've been struggling to find out why all special characters in the CSV output got replaced by a question mark, and it seems this line is responsible:

``CsvWriter csvWriter = new CsvWriter( out, delimiter, Charset.forName( "us-ascii" )  );``

Since the output is printed to System.out anyway, the system default charset is possibly more appropiate here. This would allow us to run the program with -Dfile.encoding=...

**Comment by stdunbar** [comment]
Closing old issue
